csvs/urls.py
from django.urls import path

from csvs import views

app_name = 'csvs'

urlpatterns = [
    path('', views.upload_file_view, name='upload-view'),
]

customers/urls.py
from django.urls import path

from customers import views

app_name = 'customers'

urlpatterns = [
    path('', views.customer_corr_view, name='main-customer-view'),
]

datascience/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from datascience import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),
    path('performance/', include('products.urls', namespace='products')),
    path('upload/', include('csvs.urls', namespace='csvs')),
    path('customers/', include('customers.urls', namespace='customers')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path

from products import views

app_name = 'products'

urlpatterns = [
    path('', views.chart_select_view, name='main-products-view'),
    path('add/', views.add_purchase_view, name='add-purchase-view'),
    path('sales/', views.sales_dist_view, name='sales-view'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!--    Required meta tag-->
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <!--    jQuery-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--    Semantic UI-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css" rel="stylesheet"
          type="text/css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.js"></script>
    <title>Datascience{% block title %}{% endblock title %}</title>
    <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
{% block content %}{% endblock content %}
<script src="{% static 'main.js' %}"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home {% endblock title %}
{% block content %}
<div class="block-center">
    <h2>Data Analysis with Django</h2><br><br>
    <img src="{% static 'Home.jpg' %}" height="490px" width="100%">
</div>
{% endblock content %}

templates/navbar.html
{% url 'home' as path_to_home %}
{% url 'products:main-products-view' as path_to_performance %}
{% url 'products:add-purchase-view' as path_to_adding_records %}
{% url 'csvs:upload-view' as path_to_upload %}
{% url 'customers:main-customer-view' as path_to_customers %}
{% url 'products:sales-view' as path_to_sales_view %}

<div class="ui secondary pointing menu">
    <a class="{% if request.path == path_to_home %}active{% endif %}item" href="{{ path_to_home }}">
        Home
    </a>
    <a class="{% if request.path == path_to_performance %}active{% endif %}item" href="{{ path_to_performance }}">
        Performance
    </a>
    <a class="{% if request.path == path_to_adding_records %}active{% endif %}item" href="{{ path_to_adding_records }}">
        Add records
    </a>
    <a class="{% if request.path == path_to_sales_view %}active{% endif %}item" href="{{ path_to_sales_view }}">
        Sales view
    </a>
    <a class="{% if request.path == path_to_customers %}active{% endif %}item" href="{{ path_to_customers }}">
        Customers
    </a>
    <a class="{% if request.path == path_to_upload %}active{% endif %}item" href="{{ path_to_upload }}">
        Upload file
    </a>
    <div class="right menu">
        <a class="ui item">
            Logout
        </a>
    </div>
</div>
<div class="ui segment">
    <p></p>
</div>